name: OpenAPI

on:
  push:
    branches: [ main ]
  pull_request:

permissions: read-all

jobs:
  generate-library:
    name: Generate library
    runs-on: ubuntu-latest
    permissions: read-all
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate Angular Client
        uses: openapi-generators/openapitools-generator-action@v1
        with:
          generator: typescript-fetch
          generator-tag: v6.6.0
          openapi-url: https://petstore3.swagger.io/api/v3/openapi.json
          config-file: openapi-config.yaml

      - name: Archive artifacts
        uses: actions/upload-artifact@v3
        with:
          name: biip-tools-client
          path: typescript-fetch-client

  publish-library:
    name: Publish library
    runs-on: ubuntu-latest
    needs: [ generate-library ]
    permissions:
      contents: read
      packages: write
    steps:
      - name: Download client
        uses: actions/download-artifact@v3
        with:
          name: biip-tools-client
      - run: ls -la

#      - uses: actions/setup-node@v3
#        with:
#          node-version: '18.x'
#          registry-url: 'https://npm.pkg.github.com'
#          # Defaults to the user or organization that owns the workflow file
#          scope: '@vycius'
#      - run: ls -la

      - name: Publish client library
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
